service: ccpsdemographics-v2-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  getSchools:
    handler: src/handler.getAllSchools
    events:
      - http:
          path: /schools
          method: get
          cors: true
  getSchoolsByYear:
    handler: src/handler.getSchoolsByYear
    events:
      - http:
          path: /schools/year/{academicYear}
          method: get
          cors: true
  getSchoolById:
    handler: src/handler.getSchoolById
    events:
      - http:
          path: /schools/{schoolId}
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin