service: ccpsdemographics-v2-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  getItems:
    handler: src/handler.getItems
    events:
      - http:
          path: /items
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin